name: veksel-app

services:
  veksel:
    container_name: veksel
    build: ./
    ports:
      - 4567:4567
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_started
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE: veksel
      REDIS_HOST: ${REDIS_HOST}

  migrate:
    container_name: migration
    image: migrate/migrate
    volumes:
      - ./schema:/schema
    command: ["-path", "/schema", "-database",  "postgres://${DB_USER}:${POSTGRES_PASSWORD}@db:5432/veksel?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: veksel
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d veksel"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379