name: veksel-app

services:
  veksel:
    build: ./
    ports:
      - 4567:4567
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE: veksel

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: veksel
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d veksel"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379